import {
  BacklogItemHorizon,
  BacklogItemStatus,
  BacklogItemType,
  ExpeditionStatus,
  ExerciseTargetType,
  MarkTemplateType,
  MilestoneStatus,
  RecurrenceKind,
  WorkoutExercisePhase,
  WorkoutRoutineType,
} from "../domain/waymark";
import type {
  SeedDailyMarkAssignmentConfig,
  SeedMarkTemplateConfig,
  SeedMilestoneConfig,
  SeedPackCheckTemplateConfig,
  SeedRoutineExerciseConfig,
  WaymarkMapConfig,
} from "./types";
import { PACK_CHECK_CATALOG } from "../config/packCheckCatalog";

const WEEKDAYS = [1, 2, 3, 4, 5];
const SUPERVISING_CHECKLIST = ["Check Zalo", "Check mail", "Check Confluence", "Check Jira"];

const SCH_EXPEDITION_SEED_ID = "career.sch.expedition.smart-counter-hub-project";
const SCH_ONBOARDING_MERGE_FLOW_MILESTONE_SEED_ID = "career.sch.milestone.2026-06.international-card-onboarding-merge-flow";
const SMB_CARD_MILESTONE_SEED_ID = "career.sch.milestone.2026-06.smb-card-service-confirmation";
const ONBOARDING_MILESTONE_SEED_ID = "career.sch.milestone.2026-06.card-onboarding-release";
const CORTEX_MILESTONE_SEED_ID = "career.sch.milestone.2026-09.domestic-debit-cortex";

const SHARED_COOLDOWN_STRETCH_BLUEPRINT = [
  { sourceSeedId: "calf_stretch_left", exerciseTitle: "Calf Stretch Left", canonicalSlug: "calf-stretch-left", targetDurationSec: 30 },
  { sourceSeedId: "calf_stretch_right", exerciseTitle: "Calf Stretch Right", canonicalSlug: "calf-stretch-right", targetDurationSec: 30 },
  { sourceSeedId: "forward_bend", exerciseTitle: "Forward Bend", canonicalSlug: "forward-bend", targetDurationSec: 45 },
  {
    sourceSeedId: "kneeling_lunge_stretch_left",
    exerciseTitle: "Kneeling Lunge Stretch Left",
    canonicalSlug: "kneeling-lunge-stretch-left",
    targetDurationSec: 30,
  },
  {
    sourceSeedId: "kneeling_lunge_stretch_right",
    exerciseTitle: "Kneeling Lunge Stretch Right",
    canonicalSlug: "kneeling-lunge-stretch-right",
    targetDurationSec: 30,
  },
  {
    sourceSeedId: "levator_scapulae_stretch_left",
    exerciseTitle: "Levator Scapulae Stretch Left",
    canonicalSlug: "levator-scapulae-stretch-left",
    targetDurationSec: 30,
  },
  {
    sourceSeedId: "levator_scapulae_stretch_right",
    exerciseTitle: "Levator Scapulae Stretch Right",
    canonicalSlug: "levator-scapulae-stretch-right",
    targetDurationSec: 30,
  },
  {
    sourceSeedId: "shoulder_roll_clockwise",
    exerciseTitle: "Shoulder Roll Clockwise",
    canonicalSlug: "shoulder-roll-clockwise",
    targetDurationSec: 45,
  },
  {
    sourceSeedId: "spine_lumbar_twist_stretch_left",
    exerciseTitle: "Spine Lumbar Twist Stretch Left",
    canonicalSlug: "spine-lumbar-twist-stretch-left",
    targetDurationSec: 30,
  },
  {
    sourceSeedId: "spine_lumbar_twist_stretch_right",
    exerciseTitle: "Spine Lumbar Twist Stretch Right",
    canonicalSlug: "spine-lumbar-twist-stretch-right",
    targetDurationSec: 30,
  },
  { sourceSeedId: "glute_stretch_left", exerciseTitle: "Glute Stretch Left", canonicalSlug: "glute-stretch-left", targetDurationSec: 30 },
  { sourceSeedId: "glute_stretch_right", exerciseTitle: "Glute Stretch Right", canonicalSlug: "glute-stretch-right", targetDurationSec: 30 },
  { sourceSeedId: "cat_cow_pose", exerciseTitle: "Cat Cow Pose", canonicalSlug: "cat-cow-pose", targetDurationSec: 60 },
  { sourceSeedId: "child_pose", exerciseTitle: "Child Pose", canonicalSlug: "child-pose", targetDurationSec: 60 },
] as const;

const PACK_CHECK_TEMPLATE_CONFIGS: SeedPackCheckTemplateConfig[] = PACK_CHECK_CATALOG.map((entry) => ({
  sourceSeedId: entry.sourceSeedId,
  pathSeedId: entry.pathSeedId,
  title: entry.title,
  description: entry.description,
  surfacePolicy: entry.surfacePolicy,
  items: entry.items.map((item) => ({
    sourceSeedId: item.sourceSeedId,
    label: item.label,
    isRequired: item.isRequired,
    orderIndex: item.orderIndex,
  })),
  markRules: entry.markRules?.map((rule) => ({
    sourceSeedId: rule.sourceSeedId,
    markTemplateSeedId: rule.markTemplateSeedId,
    availableOffsetMin: rule.availableOffsetMin,
    dueOffsetMin: rule.dueOffsetMin,
  })),
}));

function buildSharedCooldownStretchExercises(routinePrefix: "day_a" | "day_a2" | "day_b" | "walk", startOrderIndex = 5) {
  return SHARED_COOLDOWN_STRETCH_BLUEPRINT.map((stretch, index) => ({
    sourceSeedId: `${routinePrefix}_${stretch.sourceSeedId}`,
    exerciseTitle: stretch.exerciseTitle,
    canonicalSlug: stretch.canonicalSlug,
    phase: WorkoutExercisePhase.Stretch,
    orderIndex: startOrderIndex + index,
    targetType: ExerciseTargetType.Timed,
    targetDurationSec: stretch.targetDurationSec,
    targetSets: 1,
  }));
}

function buildGolfWarmupExercises(routinePrefix: string) {
  const warmups = [
    ["neck_shoulder_rolls", "Neck rolls + shoulder rolls", "neck-rolls-shoulder-rolls", "10 each direction"],
    ["wrist_grip", "Wrist circles + grip squeeze", "wrist-circles-grip-squeeze", "10 each direction"],
    ["hip_hinge_posture", "Hip hinge into golf posture", "hip-hinge-golf-posture", "10"],
    ["torso_rotation", "Torso rotation in golf stance", "torso-rotation-golf-stance", "10 each side"],
    ["weight_shift", "Left-right weight shift", "left-right-weight-shift", "10"],
    ["slow_practice_swings", "Slow practice swings", "slow-practice-swings", "10"],
  ] as const;

  return warmups.map(([sourceSeedId, exerciseTitle, canonicalSlug, repsLabel], index) => ({
    sourceSeedId: `${routinePrefix}_warmup_${sourceSeedId}`,
    exerciseTitle,
    canonicalSlug,
    phase: WorkoutExercisePhase.Strength,
    orderIndex: index,
    targetType: ExerciseTargetType.RepsOnly,
    targetReps: Number.parseInt(repsLabel, 10),
    targetSets: 1,
  }));
}

function buildGolfPuttingExercises(startOrderIndex = 6): SeedRoutineExerciseConfig[] {
  const puttingPrescription = [
    { distanceCm: 60, reps: 3 },
    { distanceCm: 90, reps: 1 },
    { distanceCm: 120, reps: 2 },
    { distanceCm: 150, reps: 2 },
    { distanceCm: 180, reps: 15 },
  ] as const;

  return puttingPrescription.map(({ distanceCm, reps }, index) => ({
    sourceSeedId: `putting_${distanceCm}cm`,
    exerciseTitle: `Putting ${distanceCm} cm`,
    canonicalSlug: `putting-${distanceCm}cm`,
    phase: WorkoutExercisePhase.Strength,
    orderIndex: startOrderIndex + index,
    targetType: ExerciseTargetType.RepsOnly,
    targetReps: reps,
    targetSets: 1,
  }));
}

function buildGolfChippingExercises(
  routinePrefix: string,
  sets: Array<{ label: string; slug: string; reps: number }>,
  startOrderIndex = 6,
): SeedRoutineExerciseConfig[] {
  return sets.map((set, index) => ({
    sourceSeedId: `${routinePrefix}_${set.slug}`,
    exerciseTitle: set.label,
    canonicalSlug: `golf-${routinePrefix}-${set.slug}`,
    phase: WorkoutExercisePhase.Strength,
    orderIndex: startOrderIndex + index,
    targetType: ExerciseTargetType.RepsOnly,
    targetReps: set.reps,
    targetSets: 1,
  }));
}

function buildGolfChippingDistanceExercises(distanceM: "3" | "5" | "7", landingZoneM: string) {
  return buildGolfChippingExercises(`chipping_${distanceM}m`, [
    { label: `Chipping ${distanceM} m · ${landingZoneM} landing · Calibration`, slug: "calibration", reps: 8 },
    { label: `Chipping ${distanceM} m · ${landingZoneM} landing · Rhythm`, slug: "rhythm", reps: 8 },
    { label: `Chipping ${distanceM} m · ${landingZoneM} landing · Pressure`, slug: "pressure", reps: 8 },
  ]);
}

function buildGolfChippingTestExercises() {
  const distances = [
    { distanceM: "3", landingZoneM: "1.2" },
    { distanceM: "5", landingZoneM: "2.0" },
    { distanceM: "7", landingZoneM: "2.8" },
  ] as const;

  return buildGolfChippingExercises(
    "chipping_3_5_7m",
    [1, 2].flatMap((round) =>
      distances.map(({ distanceM, landingZoneM }) => ({
        label: `Chipping ${distanceM} m · ${landingZoneM} m landing · Round ${round}`,
        slug: `${distanceM}m_round_${round}`,
        reps: 4,
      })),
    ),
  );
}

function careerAssignment(input: {
  sourceSeedId: string;
  localDate: string;
  markTemplateSeedId: string;
  title: string;
  description: string;
  orderIndex: number;
  blockType: "focus_block" | "supervising_block" | "family_block";
  taskKind?: "work_focus";
  expeditionSeedId?: string;
  milestoneSeedId?: string;
}) {
  const assignment: SeedDailyMarkAssignmentConfig = {
    sourceSeedId: input.sourceSeedId,
    localDate: input.localDate,
    markTemplateSeedId: input.markTemplateSeedId,
    title: input.title,
    description: input.description,
    orderIndex: input.orderIndex,
    blockType: input.blockType,
    taskKind: input.taskKind,
    source: "weekly_coding",
    pathSeedId: input.blockType === "family_block" ? "family" : "career",
    expeditionSeedId: input.expeditionSeedId,
    milestoneSeedId: input.milestoneSeedId,
    milestoneSourceSeedId: input.milestoneSeedId,
    appearsInToday: true,
    countsAsPathProof: true,
    requiresText: false,
  };
  return assignment;
}

function familyDateTemplate(input: {
  sourceSeedId: string;
  localDate: string;
  title: string;
  description: string;
  scheduledTime: string;
  scheduledEndTime: string;
  orderIndex: number;
}) {
  const template: SeedMarkTemplateConfig = {
    sourceSeedId: input.sourceSeedId,
    pathSeedId: "family",
    title: input.title,
    description: input.description,
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Calendar },
    isActive: true,
    generation: {
      calendarDates: [input.localDate],
      scheduledTime: input.scheduledTime,
      scheduledEndTime: input.scheduledEndTime,
      orderIndex: input.orderIndex,
      blockType: "family_block",
      source: "weekly_coding",
      appearsInToday: true,
      countsAsPathProof: true,
    },
  };
  return template;
}

const schMilestones: SeedMilestoneConfig[] = [
  {
    sourceSeedId: SMB_CARD_MILESTONE_SEED_ID,
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    title: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    description: "Expedition: SCH",
    status: MilestoneStatus.Active,
    sortOrder: 0,
    orderIndex: 0,
    targetDate: "2026-07-31",
  },
  {
    sourceSeedId: ONBOARDING_MILESTONE_SEED_ID,
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    title: "Phát hành thẻ tích hợp onboarding",
    description: "Expedition: SCH",
    status: MilestoneStatus.Active,
    sortOrder: 1,
    orderIndex: 1,
    targetDate: "2026-06-30",
  },
  {
    sourceSeedId: CORTEX_MILESTONE_SEED_ID,
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    title: "Cụm tính năng thẻ ghi nợ nội địa theo dự án Cortex",
    description: "Expedition: SCH",
    status: MilestoneStatus.Planned,
    sortOrder: 2,
    orderIndex: 2,
    targetDate: "2026-09-30",
  },
];

const schLifecycleArchetypes: SeedMarkTemplateConfig[] = [
  {
    sourceSeedId: "career.sch.archetype.urd.tgyk-urd",
    pathSeedId: "career",
    title: "TGYK URD",
    description: "SCH lifecycle archetype · default estimate 1 block · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 90,
    isActive: true,
  },
  {
    sourceSeedId: "career.sch.archetype.rsd.viet-rsd",
    pathSeedId: "career",
    title: "Viết RSD",
    description: "SCH lifecycle archetype · default estimate 3 blocks minimum · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 270,
    isActive: true,
  },
  {
    sourceSeedId: "career.sch.archetype.ui.tgyk-ui",
    pathSeedId: "career",
    title: "TGYK UI",
    description: "SCH lifecycle archetype · default estimate 1 block · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 90,
    isActive: true,
  },
  {
    sourceSeedId: "career.sch.archetype.dev.transfer-support",
    pathSeedId: "career",
    title: "Họp transfer yêu cầu hỗ trợ",
    description: "SCH lifecycle archetype · default estimate 1 block · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 90,
    isActive: true,
  },
  {
    sourceSeedId: "career.sch.archetype.sit.tao-testcase",
    pathSeedId: "career",
    title: "Tạo Testcase",
    description: "SCH lifecycle archetype · default estimate 1–2 blocks · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 180,
    isActive: true,
  },
  {
    sourceSeedId: "career.sch.archetype.sit.execute-testcase",
    pathSeedId: "career",
    title: "Execute testcase",
    description: "SCH lifecycle archetype · default estimate 1–2 blocks · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 180,
    isActive: true,
  },
  {
    sourceSeedId: "career.sch.archetype.uat.follow-bug",
    pathSeedId: "career",
    title: "Follow bug để xử lý",
    description: "SCH lifecycle archetype · default estimate 1 block · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 90,
    isActive: true,
  },
  {
    sourceSeedId: "career.sch.archetype.deploy.tgyk-checklist",
    pathSeedId: "career",
    title: "TGYK checklist",
    description: "SCH lifecycle archetype · default estimate 1 block · repeatable",
    templateType: MarkTemplateType.Routine,
    recurrenceRule: { kind: RecurrenceKind.Manual },
    defaultDurationMin: 90,
    isActive: true,
  },
];

const bidvAssignments: SeedDailyMarkAssignmentConfig[] = [
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-22.focus_block_1",
    localDate: "2026-05-22",
    markTemplateSeedId: "career.weekday.focus_block_1",
    title: "Viết RSD Template xác nhận giao dịch QLSD Thẻ trên SMB",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 2,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-22.supervising_block_am",
    localDate: "2026-05-22",
    markTemplateSeedId: "career.weekday.supervising_block_am",
    title: "Supervising Block — Check Zalo, mail, Confluence, Jira",
    description: "Daily project supervision",
    orderIndex: 3,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-22.focus_block_2",
    localDate: "2026-05-22",
    markTemplateSeedId: "career.weekday.focus_block_2",
    title: "Viết RSD API vấn tin chi tiết giao dịch QLSD Thẻ trên SCH",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 4,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-22.supervising_block_pm",
    localDate: "2026-05-22",
    markTemplateSeedId: "career.weekday.supervising_block_pm",
    title: "Supervising Block — rà blocker SCH / SMB",
    description: "Daily project supervision",
    orderIndex: 5,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-22.focus_block_3",
    localDate: "2026-05-22",
    markTemplateSeedId: "career.weekday.focus_block_3",
    title: "Buffer hoàn thiện 2 RSD ngày 22/05",
    description: "Đóng gói phần còn lại của 2 RSD",
    orderIndex: 6,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-22.family_activity",
    localDate: "2026-05-22",
    markTemplateSeedId: "family.weekday.english_block",
    title: "Family Activity Block",
    description: "Dạy con / đọc / chơi nhẹ theo tình hình",
    orderIndex: 7,
    blockType: "family_block",
  }),

  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-25.focus_block_1",
    localDate: "2026-05-25",
    markTemplateSeedId: "career.weekday.focus_block_1",
    title: "Viết RSD Cơ chế maker checker PTC chung",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 2,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-25.supervising_block_am",
    localDate: "2026-05-25",
    markTemplateSeedId: "career.weekday.supervising_block_am",
    title: "Supervising Block — Check Zalo, mail, Confluence, Jira",
    description: "Daily project supervision",
    orderIndex: 3,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-25.focus_block_2",
    localDate: "2026-05-25",
    markTemplateSeedId: "career.weekday.focus_block_2",
    title: "Xử lý Tổng hợp TGYK quy hoạch PHT GNNĐ",
    description: "Cụm tính năng thẻ ghi nợ nội địa theo dự án Cortex",
    orderIndex: 4,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: CORTEX_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-25.supervising_block_pm",
    localDate: "2026-05-25",
    markTemplateSeedId: "career.weekday.supervising_block_pm",
    title: "Rà dependency onboarding SIT",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 5,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-25.focus_block_3",
    localDate: "2026-05-25",
    markTemplateSeedId: "career.weekday.focus_block_3",
    title: "Tạo Testcase",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 6,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-25.family_activity",
    localDate: "2026-05-25",
    markTemplateSeedId: "family.weekday.english_block",
    title: "Family Activity Block",
    description: "Dạy con / chơi / đọc theo tình hình",
    orderIndex: 7,
    blockType: "family_block",
  }),

  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-26.focus_block_1",
    localDate: "2026-05-26",
    markTemplateSeedId: "career.weekday.focus_block_1",
    title: "Viết RSD Tích hợp nút xác nhận vào QLSD Thẻ",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 2,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-26.supervising_block_am",
    localDate: "2026-05-26",
    markTemplateSeedId: "career.weekday.supervising_block_am",
    title: "Supervising Block — Check Zalo, mail, Confluence, Jira",
    description: "Daily project supervision",
    orderIndex: 3,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-26.focus_block_2",
    localDate: "2026-05-26",
    markTemplateSeedId: "career.weekday.focus_block_2",
    title: "Execute testcase luồng KHCN hiện hữu",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 4,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-26.supervising_block_pm",
    localDate: "2026-05-26",
    markTemplateSeedId: "career.weekday.supervising_block_pm",
    title: "Cleanup testcase / bug log onboarding",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 5,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-26.focus_block_3",
    localDate: "2026-05-26",
    markTemplateSeedId: "career.weekday.focus_block_3",
    title: "Execute testcase luồng làm mịn KHCN",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 6,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-26.family_activity",
    localDate: "2026-05-26",
    markTemplateSeedId: "family.weekday.english_block",
    title: "Family Activity Block",
    description: "Dạy con / chơi / đọc theo tình hình",
    orderIndex: 7,
    blockType: "family_block",
  }),

  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-27.focus_block_1",
    localDate: "2026-05-27",
    markTemplateSeedId: "career.weekday.focus_block_1",
    title: "Xử lý TGYK RSD lần 1",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 2,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-27.supervising_block_am",
    localDate: "2026-05-27",
    markTemplateSeedId: "career.weekday.supervising_block_am",
    title: "Follow các điểm cần confirm từ TGYK RSD lần 1",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 3,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-27.focus_block_2",
    localDate: "2026-05-27",
    markTemplateSeedId: "career.weekday.focus_block_2",
    title: "Cập nhật RSD sau TGYK lần 1",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 4,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-27.supervising_block_pm",
    localDate: "2026-05-27",
    markTemplateSeedId: "career.weekday.supervising_block_pm",
    title: "Follow bug onboarding",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 5,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-27.focus_block_3",
    localDate: "2026-05-27",
    markTemplateSeedId: "career.weekday.focus_block_3",
    title: "Execute testcase luồng KHCN mở mới",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 6,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-27.family_activity",
    localDate: "2026-05-27",
    markTemplateSeedId: "family.weekday.english_block",
    title: "Family Activity Block",
    description: "Dạy con / chơi / đọc theo tình hình",
    orderIndex: 7,
    blockType: "family_block",
  }),

  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-28.focus_block_1",
    localDate: "2026-05-28",
    markTemplateSeedId: "career.weekday.focus_block_1",
    title: "Làm sạch RSD trước TGYK lần 2",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 2,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-28.supervising_block_am",
    localDate: "2026-05-28",
    markTemplateSeedId: "career.weekday.supervising_block_am",
    title: "Supervising Block — Check Zalo, mail, Confluence, Jira",
    description: "Daily project supervision",
    orderIndex: 3,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-28.focus_block_2",
    localDate: "2026-05-28",
    markTemplateSeedId: "career.weekday.focus_block_2",
    title: "Execute testcase luồng KHCN mở mới",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 4,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-28.supervising_block_pm",
    localDate: "2026-05-28",
    markTemplateSeedId: "career.weekday.supervising_block_pm",
    title: "Tổng hợp bug/test result onboarding",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 5,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-28.focus_block_3",
    localDate: "2026-05-28",
    markTemplateSeedId: "career.weekday.focus_block_3",
    title: "Execute testcase PHT onboarding Round 2",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 6,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-28.family_activity",
    localDate: "2026-05-28",
    markTemplateSeedId: "family.weekday.english_block",
    title: "Family Activity Block",
    description: "Dạy con / chơi / đọc theo tình hình",
    orderIndex: 7,
    blockType: "family_block",
  }),

  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-29.focus_block_1",
    localDate: "2026-05-29",
    markTemplateSeedId: "career.weekday.focus_block_1",
    title: "Xử lý TGYK RSD lần 2",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 2,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-29.supervising_block_am",
    localDate: "2026-05-29",
    markTemplateSeedId: "career.weekday.supervising_block_am",
    title: "Tổng hợp trạng thái tuần BIDV",
    description: "Cả SMB QLSD Thẻ + onboarding",
    orderIndex: 3,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-29.focus_block_2",
    localDate: "2026-05-29",
    markTemplateSeedId: "career.weekday.focus_block_2",
    title: "Xử lý TGYK RSD lần 3 & Trình ký",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 4,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-29.supervising_block_pm",
    localDate: "2026-05-29",
    markTemplateSeedId: "career.weekday.supervising_block_pm",
    title: "Chuẩn bị họp transfer yêu cầu 01/06",
    description: "Tích hợp xác nhận giao dịch qua SMB cho tính năng QLSD Thẻ — 20 tính năng",
    orderIndex: 5,
    blockType: "supervising_block",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: SMB_CARD_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-29.focus_block_3",
    localDate: "2026-05-29",
    markTemplateSeedId: "career.weekday.focus_block_3",
    title: "Execute testcase PHT onboarding Round 3",
    description: "Phát hành thẻ tích hợp onboarding",
    orderIndex: 6,
    blockType: "focus_block",
    taskKind: "work_focus",
    expeditionSeedId: SCH_EXPEDITION_SEED_ID,
    milestoneSeedId: ONBOARDING_MILESTONE_SEED_ID,
  }),
  careerAssignment({
    sourceSeedId: "daily.assignment.2026-05-29.family_activity",
    localDate: "2026-05-29",
    markTemplateSeedId: "family.weekday.english_block",
    title: "Family Activity Block",
    description: "Dạy con / chơi / đọc theo tình hình",
    orderIndex: 7,
    blockType: "family_block",
  }),
];

const healthWorkoutTestAssignments: SeedDailyMarkAssignmentConfig[] = [
  {
    sourceSeedId: "health.test.workout_day_a.2026_05_27",
    localDate: "2026-05-27",
    markTemplateSeedId: "health_test_day_a_manual",
    title: "Workout Day A",
    scheduledTime: "05:15",
    scheduledEndTime: "06:15",
    orderIndex: 2,
    blockType: "workout_block",
    source: "generated_by_engine",
    pathSeedId: "health",
    expeditionSeedId: "health.cut70.expedition",
    milestoneSeedId: "health.cut70.milestone.76kg",
    milestoneSourceSeedId: "health.cut70.milestone.76kg",
    appearsInToday: true,
    countsAsPathProof: true,
    requiresText: false,
  },
  {
    sourceSeedId: "health.test.workout_day_b.2026_05_27",
    localDate: "2026-05-27",
    markTemplateSeedId: "health_test_day_b_manual",
    title: "Workout Day B",
    scheduledTime: "06:20",
    scheduledEndTime: "07:20",
    orderIndex: 3,
    blockType: "workout_block",
    source: "generated_by_engine",
    pathSeedId: "health",
    expeditionSeedId: "health.cut70.expedition",
    milestoneSeedId: "health.cut70.milestone.76kg",
    milestoneSourceSeedId: "health.cut70.milestone.76kg",
    appearsInToday: true,
    countsAsPathProof: true,
    requiresText: false,
  },
  {
    sourceSeedId: "health.test.workout_walk.2026_05_27",
    localDate: "2026-05-27",
    markTemplateSeedId: "health_test_walk_manual",
    title: "Workout Walk",
    scheduledTime: "07:25",
    scheduledEndTime: "08:00",
    orderIndex: 4,
    blockType: "workout_block",
    source: "generated_by_engine",
    pathSeedId: "health",
    expeditionSeedId: "health.cut70.expedition",
    milestoneSeedId: "health.cut70.milestone.76kg",
    milestoneSourceSeedId: "health.cut70.milestone.76kg",
    appearsInToday: true,
    countsAsPathProof: true,
    requiresText: false,
  },
];

const familyWeekendTemplates: SeedMarkTemplateConfig[] = [
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-23.morning.play-with-kid",
    localDate: "2026-05-23",
    title: "Chơi với con buổi sáng",
    description: "Block sáng thứ 7 là chơi",
    scheduledTime: "09:00",
    scheduledEndTime: "11:00",
    orderIndex: 2,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-23.afternoon.english-class",
    localDate: "2026-05-23",
    title: "Đưa con đi học tiếng Anh",
    description: "Lịch cố định của con",
    scheduledTime: "14:00",
    scheduledEndTime: "15:00",
    orderIndex: 3,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-23.afternoon.optional-cultural-rest",
    localDate: "2026-05-23",
    title: "Hoạt động văn hóa nhẹ / nghỉ trước khi về cụ",
    description: "Optional light cultural activity or rest",
    scheduledTime: "15:15",
    scheduledEndTime: "16:45",
    orderIndex: 4,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-23.evening.visit-grandma",
    localDate: "2026-05-23",
    title: "Về cụ chơi với cụ",
    description: "Family time với cụ",
    scheduledTime: "19:00",
    scheduledEndTime: "21:00",
    orderIndex: 5,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-24.morning.drawing-class",
    localDate: "2026-05-24",
    title: "Đưa con đi học vẽ",
    description: "Lịch cố định của con",
    scheduledTime: "09:00",
    scheduledEndTime: "10:30",
    orderIndex: 2,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-24.afternoon.recovery",
    localDate: "2026-05-24",
    title: "Recovery gia đình / chơi nhẹ trong nhà",
    description: "Giữ sức trước BIDV-heavy week",
    scheduledTime: "13:30",
    scheduledEndTime: "15:00",
    orderIndex: 3,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-24.evening.movie",
    localDate: "2026-05-24",
    title: "Đi xem phim Doraemon",
    description: "Family movie activity",
    scheduledTime: "19:00",
    scheduledEndTime: "21:00",
    orderIndex: 4,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-30.morning.menu-list",
    localDate: "2026-05-30",
    title: "Chọn món + lên danh sách đồ cần mua",
    description: "Nấu ăn cho gia đình",
    scheduledTime: "09:00",
    scheduledEndTime: "10:00",
    orderIndex: 2,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-30.morning.buy-ingredients",
    localDate: "2026-05-30",
    title: "Đi chợ / mua nguyên liệu",
    description: "Nấu ăn cho gia đình",
    scheduledTime: "10:15",
    scheduledEndTime: "11:30",
    orderIndex: 3,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-30.afternoon.prep-cooking",
    localDate: "2026-05-30",
    title: "Sơ chế + chuẩn bị nấu ăn gia đình",
    description: "Nấu ăn cho gia đình",
    scheduledTime: "13:30",
    scheduledEndTime: "15:00",
    orderIndex: 4,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-30.afternoon.cook-for-family",
    localDate: "2026-05-30",
    title: "Nấu ăn cho gia đình",
    description: "Family cooking activity",
    scheduledTime: "16:00",
    scheduledEndTime: "17:30",
    orderIndex: 5,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-30.evening.family-dinner",
    localDate: "2026-05-30",
    title: "Ăn tối gia đình + dọn dẹp nhẹ",
    description: "Family dinner",
    scheduledTime: "19:00",
    scheduledEndTime: "21:00",
    orderIndex: 6,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-31.morning.ice-cream-expo",
    localDate: "2026-05-31",
    title: "Đi Triển lãm Kem Việt Nam 2026 — Vietnam Ice Cream Expo",
    description: "Cung Văn hoá Lao động Hữu nghị Việt Xô, 91 Trần Hưng Đạo, Hà Nội",
    scheduledTime: "09:00",
    scheduledEndTime: "12:00",
    orderIndex: 2,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-31.afternoon.recovery-next-week",
    localDate: "2026-05-31",
    title: "Recovery + chuẩn bị tuần mới",
    description: "Reset nhà / đồ / lịch tuần",
    scheduledTime: "13:30",
    scheduledEndTime: "15:00",
    orderIndex: 3,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-31.final.family-reset",
    localDate: "2026-05-31",
    title: "Nghỉ / chuẩn bị đồ đi làm / family reset nhẹ",
    description: "Giữ sức trước tuần mới",
    scheduledTime: "17:00",
    scheduledEndTime: "18:30",
    orderIndex: 4,
  }),
  familyDateTemplate({
    sourceSeedId: "family.plan.2026-05-31.evening.andersen-backup",
    localDate: "2026-05-31",
    title: "Truyện cổ Andersen — optional backup",
    description: "Chỉ đi nếu cả nhà còn sức",
    scheduledTime: "20:00",
    scheduledEndTime: "21:00",
    orderIndex: 5,
  }),
];

function seededMilestone(
  sourceSeedId: string,
  expeditionSeedId: string,
  title: string,
  targetDate: string | undefined,
  sortOrder: number,
  status: MilestoneStatus = MilestoneStatus.Active,
  description?: string,
): SeedMilestoneConfig {
  return {
    sourceSeedId,
    expeditionSeedId,
    title,
    description: description ?? `Expedition: ${expeditionSeedId}`,
    status,
    sortOrder,
    orderIndex: sortOrder,
    targetDate,
  };
}

const MASTER_MILESTONES: SeedMilestoneConfig[] = [
  seededMilestone(SCH_ONBOARDING_MERGE_FLOW_MILESTONE_SEED_ID, SCH_EXPEDITION_SEED_ID, "Phát hànhThẻ GNQT — Ghép luồng Onboarding", "2026-06-20", 0, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone(SMB_CARD_MILESTONE_SEED_ID, SCH_EXPEDITION_SEED_ID, "OBD Thẻ GNQT — Quản lý sự đồng ý của KH", "2026-07-31", 1, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-08.credit-card-debt-collection-adjustment", SCH_EXPEDITION_SEED_ID, "GD tài chính thẻ tín dụng — Thu nợ & điều chỉnh thu nợ", "2026-08-31", 2, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-08.statement-cycle-limit-adjustment", SCH_EXPEDITION_SEED_ID, "Điều chỉnh hạn mức giao dịch thẻ theo kỳ sao kê — đợt tháng 8", "2026-08-31", 3, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-08.auto-qlsd-form", SCH_EXPEDITION_SEED_ID, "Tự động lập Biểu mẫu QLSD Thẻ", "2026-08-31", 4, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone(ONBOARDING_MILESTONE_SEED_ID, SCH_EXPEDITION_SEED_ID, "Xác nhận 20 tính năng QLSD thẻ trên SMB", "2026-08-31", 5, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-09.statement-cycle-limit-adjustment", SCH_EXPEDITION_SEED_ID, "Điều chỉnh hạn mức giao dịch thẻ theo kỳ sao kê — đợt tháng 9", "2026-09-30", 6, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-09.card-art-reissue-renewal", SCH_EXPEDITION_SEED_ID, "Card Art — Phát hành lại và gia hạn thẻ", "2026-09-30", 7, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-09.jcb-hb-funding-source-switch", SCH_EXPEDITION_SEED_ID, "Đổi nguồn tiền giao dịch JCB HB & QLSD thay đổi nguồn tiền", "2026-09-30", 8, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone(CORTEX_MILESTONE_SEED_ID, SCH_EXPEDITION_SEED_ID, "QLSD thẻ GNND theo dự án Cortex", "2026-10-31", 9, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-10.domestic-debit-card-issuance-cortex", SCH_EXPEDITION_SEED_ID, "Phát hành thẻ GNND theo dự án Cortex", "2026-10-31", 10, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-10.international-domestic-debit-pht", SCH_EXPEDITION_SEED_ID, "PHT ghi nợ quốc tế/nội địa", "2026-10-31", 11, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-10.bulk-card-renewal", SCH_EXPEDITION_SEED_ID, "Gia hạn thẻ theo lô", "2026-10-31", 12, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-11.personal-hybrid-credit-pht-with-limit", SCH_EXPEDITION_SEED_ID, "PHT tín dụng cá nhân/Hybrid — đã có HMTD & HMTD 0 đồng", "2026-11-30", 13, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-11.hybrid-no-limit-card-art", SCH_EXPEDITION_SEED_ID, "PHT Hybrid chưa có HMTD — bổ sung lựa chọn Card Art", "2026-11-30", 14, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-11.anonymous-prepaid-bulk", SCH_EXPEDITION_SEED_ID, "Thẻ trả trước quốc tế vô danh theo lô", "2026-11-30", 15, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("career.sch.milestone.2026-12.card-interest-fee-collection-reversal", SCH_EXPEDITION_SEED_ID, "GD lãi/phí thẻ — thu và hủy", "2026-12-31", 16, MilestoneStatus.Active, "Expedition: SCH"),
  seededMilestone("snag.growth.milestone.dashboard-analysis", "snag.growth.expedition", "Tạo Dashboard phân tích bài", "2026-06-30", 0),
  seededMilestone("snag.growth.milestone.content-foundation", "snag.growth.expedition", "Content foundation", "2026-07-30", 1),
  seededMilestone("family.english.milestone.grammar-book", "family.english.expedition", "Đọc xong sách ngữ pháp tiếng Anh cho con", "2026-07-30", 0),
  seededMilestone("family.weekend.milestone.golf-tournament-memory", "family.weekend.expedition", "Family golf memory / tournament day", "2026-06-27", 0),
  seededMilestone("family.weekend.milestone.lotus-festival-west-lake", "family.weekend.expedition", "Family memory — Tây Hồ", "2026-06-28", 1),
  seededMilestone("family.rhythm.milestone.weekend-recovery", "family.rhythm.expedition", "Recovery sau weekend di chuyển nhiều", "2026-06-28", 0),
  seededMilestone("family.vietnam-trip.milestone.ninh-binh", "family.vietnam-trip.expedition", "Ninh Bình tháng 9/2026", "2026-09-01", 0),
  seededMilestone("family.waymark.milestone.anniversary-edition", "family.waymark.expedition", "Xây dựng Waymark Anniversary edition", "2026-06-12", 0),
  seededMilestone("health.cut70.milestone.76kg", "health.cut70.expedition", "Reach 76kg", "2026-06-30", 0),
  seededMilestone("health.cut70.milestone.75kg", "health.cut70.expedition", "Reach 75kg", "2026-07-31", 1),
  seededMilestone("health.cut70.milestone.74kg", "health.cut70.expedition", "Reach 74kg", "2026-08-31", 2),
  seededMilestone("health.cut70.milestone.73kg", "health.cut70.expedition", "Reach 73kg", "2026-09-30", 3),
  seededMilestone("health.cut70.milestone.72kg", "health.cut70.expedition", "Reach 72kg", "2026-10-31", 4),
  seededMilestone("health.cut70.milestone.71kg", "health.cut70.expedition", "Reach 71kg", "2026-11-30", 5),
  seededMilestone("health.cut70.milestone.70kg", "health.cut70.expedition", "Reach 70kg", "2026-12-31", 6),
  seededMilestone("golf.beginning.milestone.home-snag-phase", "golf.beginning.expedition", "Home and SNAG practice phase", "2026-08-15", 0),
];

export const WAYMARK_MAP_CONFIG: WaymarkMapConfig = {
  version: 10,
  paths: [
    { sourceSeedId: "career", slug: "career", title: "Career", sortOrder: 0 },
    { sourceSeedId: "snag", slug: "snag-golf-vietnam", title: "SNAG Golf Vietnam", sortOrder: 1 },
    { sourceSeedId: "family", slug: "family-home", title: "Family & Home", sortOrder: 2 },
    { sourceSeedId: "health", slug: "health-body", title: "Health & Body", sortOrder: 3 },
    { sourceSeedId: "style", slug: "style-class", title: "Style & Class", sortOrder: 4 },
    { sourceSeedId: "golf", slug: "golf-craft", title: "Golf Craft", sortOrder: 5 },
    { sourceSeedId: "character", slug: "stoicism-character", title: "Stoicism & Character", sortOrder: 6 },
  ],
  expeditions: [
    {
      sourceSeedId: SCH_EXPEDITION_SEED_ID,
      pathSeedId: "career",
      title: "SCH Smart Counter Hub Project",
      description: "Career expedition for BIDV-heavy delivery work.",
      status: ExpeditionStatus.Active,
      sortOrder: 0,
    },
    {
      sourceSeedId: "snag.growth.expedition",
      pathSeedId: "snag",
      title: "SNAG Golf Vietnam Growth",
      status: ExpeditionStatus.Active,
      sortOrder: 0,
    },
    {
      sourceSeedId: "family.english.expedition",
      pathSeedId: "family",
      title: "Dạy con Tiếng Anh",
      status: ExpeditionStatus.Active,
      sortOrder: 0,
    },
    {
      sourceSeedId: "family.waymark.expedition",
      pathSeedId: "family",
      title: "Building Waymark",
      status: ExpeditionStatus.Active,
      sortOrder: 1,
      targetDate: "2026-06-12",
    },
    {
      sourceSeedId: "family.weekend.expedition",
      pathSeedId: "family",
      title: "Family Weekend",
      status: ExpeditionStatus.Active,
      sortOrder: 2,
      targetDate: "2026-06-28",
    },
    {
      sourceSeedId: "family.rhythm.expedition",
      pathSeedId: "family",
      title: "Family rhythm",
      status: ExpeditionStatus.Active,
      sortOrder: 3,
      targetDate: "2026-06-28",
    },
    {
      sourceSeedId: "family.vietnam-trip.expedition",
      pathSeedId: "family",
      title: "Kế hoạch Du lịch Việt Nam",
      status: ExpeditionStatus.Active,
      sortOrder: 4,
      targetDate: "2026-09-01",
    },
    {
      sourceSeedId: "health.cut70.expedition",
      pathSeedId: "health",
      title: "Cut to 70",
      status: ExpeditionStatus.Active,
      sortOrder: 0,
      targetDate: "2026-12-31",
    },
    {
      sourceSeedId: "golf.beginning.expedition",
      pathSeedId: "golf",
      title: "Beginning: From SNAG to 3D Line",
      status: ExpeditionStatus.Active,
      sortOrder: 0,
      startDate: "2026-06-15",
      targetDate: "2026-09-15",
    },
  ],
  milestones: MASTER_MILESTONES,
  markTemplates: [
    {
      sourceSeedId: "career.weekday.focus_block_1",
      pathSeedId: "career",
      title: "Focus Block 1",
      templateType: MarkTemplateType.Routine,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: WEEKDAYS },
      isActive: true,
      generation: {
        scheduledTime: "08:00",
        scheduledEndTime: "09:30",
        orderIndex: 2,
        blockType: "focus_block",
        taskKind: "work_focus",
        source: "weekly_coding",
        appearsInToday: true,
        countsAsPathProof: true,
      },
    },
    {
      sourceSeedId: "career.weekday.supervising_block_am",
      pathSeedId: "career",
      title: "Supervising Block — morning",
      templateType: MarkTemplateType.Routine,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: WEEKDAYS },
      isActive: true,
      generation: {
        scheduledTime: "10:00",
        scheduledEndTime: "11:30",
        orderIndex: 3,
        blockType: "supervising_block",
        source: "weekly_coding",
        appearsInToday: true,
        countsAsPathProof: true,
        executionChecklistItems: SUPERVISING_CHECKLIST,
      },
    },
    {
      sourceSeedId: "career.weekday.focus_block_2",
      pathSeedId: "career",
      title: "Focus Block 2",
      templateType: MarkTemplateType.Routine,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: WEEKDAYS },
      isActive: true,
      generation: {
        scheduledTime: "13:30",
        scheduledEndTime: "15:00",
        orderIndex: 4,
        blockType: "focus_block",
        taskKind: "work_focus",
        source: "weekly_coding",
        appearsInToday: true,
        countsAsPathProof: true,
      },
    },
    {
      sourceSeedId: "career.weekday.supervising_block_pm",
      pathSeedId: "career",
      title: "Supervising Block — afternoon",
      templateType: MarkTemplateType.Routine,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: WEEKDAYS },
      isActive: true,
      generation: {
        scheduledTime: "15:15",
        scheduledEndTime: "16:45",
        orderIndex: 5,
        blockType: "supervising_block",
        source: "weekly_coding",
        appearsInToday: true,
        countsAsPathProof: true,
        executionChecklistItems: SUPERVISING_CHECKLIST,
      },
    },
    {
      sourceSeedId: "career.weekday.focus_block_3",
      pathSeedId: "career",
      title: "Focus Block 3",
      templateType: MarkTemplateType.Routine,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: WEEKDAYS },
      isActive: true,
      generation: {
        scheduledTime: "17:00",
        scheduledEndTime: "18:30",
        orderIndex: 6,
        blockType: "focus_block",
        taskKind: "work_focus",
        source: "weekly_coding",
        appearsInToday: true,
        countsAsPathProof: true,
      },
    },
    {
      sourceSeedId: "family.weekday.english_block",
      pathSeedId: "family",
      title: "Family Activity Block",
      templateType: MarkTemplateType.Routine,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: WEEKDAYS },
      isActive: true,
      generation: {
        scheduledTime: "20:00",
        scheduledEndTime: "21:00",
        orderIndex: 7,
        blockType: "family_block",
        source: "weekly_coding",
        appearsInToday: true,
        countsAsPathProof: true,
      },
    },
    {
      sourceSeedId: "health_day_a_strength",
      pathSeedId: "health",
      title: "Workout A1",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.CustomCycle, customCycleKey: "health_cycle", customCycleIndex: 0 },
      isActive: true,
      generation: {
        startDate: "2026-05-19",
        scheduledTime: "05:00",
        scheduledEndTime: "07:30",
        orderIndex: 1,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_day_b_strength",
      pathSeedId: "health",
      title: "Workout B",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.CustomCycle, customCycleKey: "health_cycle", customCycleIndex: 1 },
      isActive: true,
      generation: {
        startDate: "2026-05-19",
        scheduledTime: "05:00",
        scheduledEndTime: "07:30",
        orderIndex: 1,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_walk_day_1",
      pathSeedId: "health",
      title: "Workout Walk",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.CustomCycle, customCycleKey: "health_cycle", customCycleIndex: 2 },
      isActive: true,
      generation: {
        startDate: "2026-05-19",
        scheduledTime: "05:00",
        scheduledEndTime: "07:30",
        orderIndex: 1,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_day_a2_strength",
      pathSeedId: "health",
      title: "Workout A2",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.CustomCycle, customCycleKey: "health_cycle", customCycleIndex: 3 },
      isActive: true,
      generation: {
        startDate: "2026-05-19",
        scheduledTime: "05:00",
        scheduledEndTime: "07:30",
        orderIndex: 1,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_day_b_2_strength",
      pathSeedId: "health",
      title: "Workout B",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.CustomCycle, customCycleKey: "health_cycle", customCycleIndex: 4 },
      isActive: true,
      generation: {
        startDate: "2026-05-19",
        scheduledTime: "05:00",
        scheduledEndTime: "07:30",
        orderIndex: 1,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_walk_day_2",
      pathSeedId: "health",
      title: "Workout Walk",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.CustomCycle, customCycleKey: "health_cycle", customCycleIndex: 5 },
      isActive: true,
      generation: {
        startDate: "2026-05-19",
        scheduledTime: "05:00",
        scheduledEndTime: "07:30",
        orderIndex: 1,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_walk_day_3",
      pathSeedId: "health",
      title: "Workout Walk",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.CustomCycle, customCycleKey: "health_cycle", customCycleIndex: 6 },
      isActive: true,
      generation: {
        startDate: "2026-05-19",
        scheduledTime: "05:00",
        scheduledEndTime: "07:30",
        orderIndex: 1,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_test_day_a_manual",
      pathSeedId: "health",
      title: "Workout Day A",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: [3] },
      isActive: true,
      generation: {
        startDate: "2026-05-27",
        scheduledTime: "05:15",
        scheduledEndTime: "06:15",
        orderIndex: 2,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_test_day_b_manual",
      pathSeedId: "health",
      title: "Workout Day B",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: [3] },
      isActive: true,
      generation: {
        startDate: "2026-05-27",
        scheduledTime: "06:20",
        scheduledEndTime: "07:20",
        orderIndex: 3,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_test_walk_manual",
      pathSeedId: "health",
      title: "Workout Walk",
      templateType: MarkTemplateType.Workout,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: [3] },
      isActive: true,
      generation: {
        startDate: "2026-05-27",
        scheduledTime: "07:25",
        scheduledEndTime: "08:00",
        orderIndex: 4,
        blockType: "workout_block",
        source: "generated_by_engine",
        appearsInToday: true,
        countsAsPathProof: true,
        expeditionSeedId: "health.cut70.expedition",
        milestoneSeedId: "health.cut70.milestone.76kg",
        milestoneSourceSeedId: "health.cut70.milestone.76kg",
      },
    },
    {
      sourceSeedId: "health_weekly_weight",
      pathSeedId: "health",
      title: "Weekly Weight Input",
      templateType: MarkTemplateType.Routine,
      recurrenceRule: { kind: RecurrenceKind.Weekly, daysOfWeek: [6] },
      isActive: true,
      generation: { scheduledTime: "08:00", measurementType: "weight" },
    },
    {
      sourceSeedId: "style_quarterly_reset",
      pathSeedId: "style",
      title: "Quarterly Wardrobe Reset",
      templateType: MarkTemplateType.Ritual,
      recurrenceRule: { kind: RecurrenceKind.Calendar },
      isActive: true,
      generation: {
        calendarDates: ["2026-07-04", "2026-10-03", "2027-01-02", "2027-04-03", "2027-07-03", "2027-10-02"],
      },
    },
    ...schLifecycleArchetypes,
    ...familyWeekendTemplates,
  ],
  dailyMarkAssignments: [...bidvAssignments, ...healthWorkoutTestAssignments],
  packCheckTemplates: PACK_CHECK_TEMPLATE_CONFIGS,
  backlogItems: [
    {
      sourceSeedId: "career_aws",
      pathSeedId: "career",
      title: "AWS Solution Architecture",
      itemType: BacklogItemType.Project,
      horizon: BacklogItemHorizon.Someday,
      status: BacklogItemStatus.Open,
    },
    {
      sourceSeedId: "career_pmp",
      pathSeedId: "career",
      title: "PMP",
      itemType: BacklogItemType.Project,
      horizon: BacklogItemHorizon.Someday,
      status: BacklogItemStatus.Open,
    },
    {
      sourceSeedId: "career_cbap",
      pathSeedId: "career",
      title: "CBAP Recertification",
      itemType: BacklogItemType.Project,
      horizon: BacklogItemHorizon.Someday,
      status: BacklogItemStatus.Open,
    },
    {
      sourceSeedId: "snag_monetization",
      pathSeedId: "snag",
      title: "SNAG Golf monetization",
      itemType: BacklogItemType.Project,
      horizon: BacklogItemHorizon.Someday,
      status: BacklogItemStatus.Open,
    },
    {
      sourceSeedId: "family_yard_sale",
      pathSeedId: "family",
      title: "Dọn nhà Yard Sale",
      itemType: BacklogItemType.Project,
      horizon: BacklogItemHorizon.Someday,
      status: BacklogItemStatus.Open,
    },
    {
      sourceSeedId: "health_67kg",
      pathSeedId: "health",
      title: "67kg later target",
      itemType: BacklogItemType.Project,
      horizon: BacklogItemHorizon.Someday,
      status: BacklogItemStatus.Open,
    },
    {
      sourceSeedId: "golf_outing",
      pathSeedId: "golf",
      title: "Outing",
      itemType: BacklogItemType.Project,
      horizon: BacklogItemHorizon.Someday,
      status: BacklogItemStatus.Open,
    },
    {
      sourceSeedId: "character_discipline_standard",
      pathSeedId: "character",
      title: "Define Discipline to Keep standard later",
      itemType: BacklogItemType.Note,
      horizon: BacklogItemHorizon.Unplanned,
      status: BacklogItemStatus.Open,
    },
  ],
  signalConfigs: [
    {
      sourceSeedId: "global_close_day",
      label: "Close the Trail Signal",
      targetType: "global",
      scheduledTime: "21:30",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "health_day_a1_wake_signal",
      label: "Gym / Workout Wake Signal",
      targetType: "mark_template",
      targetSeedId: "health_day_a_strength",
      scheduledTime: "05:30",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "health_day_b1_wake_signal",
      label: "Gym / Workout Wake Signal",
      targetType: "mark_template",
      targetSeedId: "health_day_b_strength",
      scheduledTime: "05:30",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "health_workout_readiness_signal",
      label: "Workout Readiness Check Signal",
      targetType: "pack_check_template",
      targetSeedId: "health.workout-readiness-check",
      scheduledTime: "21:00",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "health_day_a2_wake_signal",
      label: "Gym / Workout Wake Signal",
      targetType: "mark_template",
      targetSeedId: "health_day_a2_strength",
      scheduledTime: "05:30",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "health_day_b2_wake_signal",
      label: "Gym / Workout Wake Signal",
      targetType: "mark_template",
      targetSeedId: "health_day_b_2_strength",
      scheduledTime: "05:30",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "health_walk_readiness_signal",
      label: "Walk Readiness Check Signal",
      targetType: "pack_check_template",
      targetSeedId: "health.walk-readiness-check",
      scheduledTime: "21:00",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "health_weekly_weight_signal",
      label: "Weekly Weight Signal",
      targetType: "mark_template",
      targetSeedId: "health_weekly_weight",
      scheduledTime: "08:00",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "style_grooming_morning_signal",
      label: "Daily Grooming Morning Signal",
      targetType: "pack_check_template",
      targetSeedId: "style.daily-grooming-presence-check",
      scheduledTime: "07:45",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
    {
      sourceSeedId: "style_grooming_midday_signal",
      label: "Daily Grooming Midday Signal",
      targetType: "pack_check_template",
      targetSeedId: "style.daily-grooming-presence-check",
      scheduledTime: "13:15",
      repeatAfterMinutes: 5,
      maxRings: 3,
      strict: true,
      isActive: true,
    },
  ],
  workoutRoutines: [
    {
      sourceSeedId: "health_day_a_routine",
      pathSeedId: "health",
      markTemplateSeedId: "health_day_a_strength",
      title: "Day A1 Strength",
      routineType: WorkoutRoutineType.Strength,
      isActive: true,
      exercises: [
        {
          sourceSeedId: "squat",
          exerciseTitle: "Barbell Squat",
          canonicalSlug: "barbell-squat",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 0,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 60,
          targetReps: 5,
          targetSets: 3,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "bench",
          exerciseTitle: "Barbell Bench Press",
          canonicalSlug: "barbell-bench-press",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 1,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 45,
          targetReps: 8,
          targetSets: 2,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "pallof_press",
          exerciseTitle: "Pallof Press",
          canonicalSlug: "pallof-press",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 2,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 15,
          targetReps: 10,
          targetSets: 2,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "plank",
          exerciseTitle: "Plank",
          canonicalSlug: "plank",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 3,
          targetType: ExerciseTargetType.Timed,
          targetDurationSec: 50,
          targetSets: 1,
        },
        ...buildSharedCooldownStretchExercises("day_a", 4),
      ],
    },
    {
      sourceSeedId: "health_day_a2_routine",
      pathSeedId: "health",
      markTemplateSeedId: "health_day_a2_strength",
      title: "Day A2 Strength",
      routineType: WorkoutRoutineType.Strength,
      isActive: true,
      exercises: [
        {
          sourceSeedId: "squat",
          exerciseTitle: "Barbell Squat",
          canonicalSlug: "barbell-squat",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 0,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 60,
          targetReps: 5,
          targetSets: 3,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "press",
          exerciseTitle: "Standing Barbell Military Press",
          canonicalSlug: "standing-barbell-military-press",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 1,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 24,
          targetReps: 8,
          targetSets: 2,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "pallof_press",
          exerciseTitle: "Pallof Press",
          canonicalSlug: "pallof-press",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 2,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 15,
          targetReps: 10,
          targetSets: 2,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "plank",
          exerciseTitle: "Plank",
          canonicalSlug: "plank",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 3,
          targetType: ExerciseTargetType.Timed,
          targetDurationSec: 50,
          targetSets: 1,
        },
        ...buildSharedCooldownStretchExercises("day_a2", 4),
      ],
    },
    {
      sourceSeedId: "health_day_b_routine",
      pathSeedId: "health",
      markTemplateSeedId: "health_day_b_strength",
      title: "Day B Strength",
      routineType: WorkoutRoutineType.Strength,
      isActive: true,
      exercises: [
        {
          sourceSeedId: "deadlift",
          exerciseTitle: "Barbell Deadlift",
          canonicalSlug: "barbell-deadlift",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 0,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 70,
          targetReps: 5,
          targetSets: 3,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "row",
          exerciseTitle: "Bent Over Barbell Row",
          canonicalSlug: "bent-over-barbell-row",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 1,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 34,
          targetReps: 8,
          targetSets: 2,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "wood_chop",
          exerciseTitle: "Wood Chop",
          canonicalSlug: "wood-chop",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 2,
          targetType: ExerciseTargetType.RepsLoad,
          targetLoadKg: 10,
          targetReps: 10,
          targetSets: 1,
          restDurationSec: 90,
        },
        {
          sourceSeedId: "ab_wheel",
          exerciseTitle: "Kneeling Ab Wheel Rollout",
          canonicalSlug: "kneeling-ab-wheel-rollout",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 3,
          targetType: ExerciseTargetType.RepsOnly,
          targetReps: 10,
          targetSets: 2,
          restDurationSec: 90,
        },
        ...buildSharedCooldownStretchExercises("day_b", 4),
      ],
    },
    {
      sourceSeedId: "health_walk_routine",
      pathSeedId: "health",
      title: "Walk Day",
      routineType: WorkoutRoutineType.Walk,
      cycleKey: "health_cycle",
      isActive: true,
      exercises: [
        {
          sourceSeedId: "walk_block",
          exerciseTitle: "Walk",
          canonicalSlug: "walk-day",
          phase: WorkoutExercisePhase.Walk,
          orderIndex: 0,
          targetType: ExerciseTargetType.Timed,
          targetDurationSec: 1800,
          targetSets: 1,
        },
        ...buildSharedCooldownStretchExercises("walk", 1),
      ],
    },
    {
      sourceSeedId: "golf_practice_putting_routine",
      pathSeedId: "golf",
      title: "Golf Practice Putting 23 Putts",
      description: "Golf Craft putting prescription: 60 cm x3, 90 cm x1, 120 cm x2, 150 cm x2, 180 cm x15.",
      routineType: WorkoutRoutineType.GolfPractice,
      estimatedDurationMin: 25,
      isActive: true,
      exercises: [
        ...buildGolfWarmupExercises("putting"),
        ...buildGolfPuttingExercises(6),
      ],
    },
    {
      sourceSeedId: "golf_practice_chipping_3m_routine",
      pathSeedId: "golf",
      title: "Golf Practice Chipping 3 m",
      description: "Golf Craft chipping: 3 sets x 8 reps, land inside 1.2 m zone and hit Flagsticky.",
      routineType: WorkoutRoutineType.GolfPractice,
      estimatedDurationMin: 30,
      isActive: true,
      exercises: [
        ...buildGolfWarmupExercises("chipping_3m"),
        ...buildGolfChippingDistanceExercises("3", "1.2 m"),
      ],
    },
    {
      sourceSeedId: "golf_practice_chipping_5m_routine",
      pathSeedId: "golf",
      title: "Golf Practice Chipping 5 m",
      description: "Golf Craft chipping: 3 sets x 8 reps, land inside 2.0 m zone and hit Flagsticky.",
      routineType: WorkoutRoutineType.GolfPractice,
      estimatedDurationMin: 30,
      isActive: true,
      exercises: [
        ...buildGolfWarmupExercises("chipping_5m"),
        ...buildGolfChippingDistanceExercises("5", "2.0 m"),
      ],
    },
    {
      sourceSeedId: "golf_practice_chipping_7m_routine",
      pathSeedId: "golf",
      title: "Golf Practice Chipping 7 m",
      description: "Golf Craft chipping: 3 sets x 8 reps, land inside 2.8 m zone and hit Flagsticky.",
      routineType: WorkoutRoutineType.GolfPractice,
      estimatedDurationMin: 30,
      isActive: true,
      exercises: [
        ...buildGolfWarmupExercises("chipping_7m"),
        ...buildGolfChippingDistanceExercises("7", "2.8 m"),
      ],
    },
    {
      sourceSeedId: "golf_practice_chipping_3_5_7m_routine",
      pathSeedId: "golf",
      title: "Golf Practice Chipping 3-5-7 m",
      description: "Golf Craft chipping test: 6 sets x 4 reps across 3 m, 5 m, and 7 m.",
      routineType: WorkoutRoutineType.GolfPractice,
      estimatedDurationMin: 30,
      isActive: true,
      exercises: [
        ...buildGolfWarmupExercises("chipping_3_5_7m"),
        ...buildGolfChippingTestExercises(),
      ],
    },
    {
      sourceSeedId: "golf_practice_swing_routine",
      pathSeedId: "golf",
      title: "Golf Practice Swing",
      description: "Log-only Golf Craft swing practice.",
      routineType: WorkoutRoutineType.GolfPractice,
      estimatedDurationMin: 35,
      isActive: true,
      exercises: [
        ...buildGolfWarmupExercises("swing"),
        {
          sourceSeedId: "swing_set_1",
          exerciseTitle: "Swing practice set 1",
          canonicalSlug: "golf-swing-practice-set-1",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 6,
          targetType: ExerciseTargetType.RepsOnly,
          targetReps: 10,
          targetSets: 1,
        },
        {
          sourceSeedId: "swing_set_2",
          exerciseTitle: "Swing practice set 2",
          canonicalSlug: "golf-swing-practice-set-2",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 7,
          targetType: ExerciseTargetType.RepsOnly,
          targetReps: 10,
          targetSets: 1,
        },
        {
          sourceSeedId: "swing_set_3",
          exerciseTitle: "Swing practice set 3",
          canonicalSlug: "golf-swing-practice-set-3",
          phase: WorkoutExercisePhase.Strength,
          orderIndex: 8,
          targetType: ExerciseTargetType.RepsOnly,
          targetReps: 10,
          targetSets: 1,
        },
      ],
    },
  ],
  closeTrailRules: [
    {
      sourceSeedId: "default_close_trail_rule",
      disciplines: [
        {
          key: "no_eating_outside_window",
          label: "No eating outside of eating window",
          pathSeedId: "health",
          expeditionSeedId: "health.cut70.expedition",
          milestoneSeedId: "health.cut70.milestone.76kg",
        },
        {
          key: "no_overeating_during_window",
          label: "No overeating during eating window",
          pathSeedId: "health",
          expeditionSeedId: "health.cut70.expedition",
          milestoneSeedId: "health.cut70.milestone.76kg",
        },
      ],
    },
  ],
  anchorPathRotations: [
    {
      sourceSeedId: "default_anchor_path_rotation",
      weekdayPathSeedIds: {
        0: "family",
        1: "career",
        2: "snag",
        3: "career",
        4: "snag",
        5: "career",
        6: "family",
      },
    },
  ],
};

export * from "./types";
export * from "./seedClassification";
