CREATE TABLE IF NOT EXISTS trail_days (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  local_date TEXT NOT NULL,
  status TEXT NOT NULL,
  anchor_path_id TEXT,
  closed_at INTEGER,
  reopened_at INTEGER,
  close_summary TEXT,
  tomorrow_first_step TEXT,
  character_result TEXT,
  planned_mark_count INTEGER NOT NULL DEFAULT 0,
  completed_mark_count INTEGER NOT NULL DEFAULT 0,
  skipped_mark_count INTEGER NOT NULL DEFAULT 0,
  memory_count INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  UNIQUE(user_id, local_date),
  FOREIGN KEY(anchor_path_id) REFERENCES paths(id)
);

CREATE TABLE IF NOT EXISTS mark_templates (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  path_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  template_type TEXT NOT NULL,
  recurrence_type TEXT NOT NULL,
  recurrence_rule_json TEXT NOT NULL,
  default_duration_min INTEGER,
  default_signal_rule_json TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(path_id) REFERENCES paths(id)
);

CREATE TABLE IF NOT EXISTS mark_instances (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  path_id TEXT NOT NULL,
  trail_day_id TEXT NOT NULL,
  template_id TEXT,
  expedition_id TEXT,
  milestone_id TEXT,
  title TEXT NOT NULL,
  description TEXT,
  origin TEXT NOT NULL,
  status TEXT NOT NULL,
  scheduled_start_at INTEGER,
  scheduled_end_at INTEGER,
  due_at INTEGER,
  completed_at INTEGER,
  skipped_at INTEGER,
  expired_at INTEGER,
  proof_note TEXT,
  completion_summary TEXT,
  substituted_by_mark_id TEXT,
  rescheduled_to_mark_id TEXT,
  source_backlog_item_id TEXT,
  generation_key TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(path_id) REFERENCES paths(id),
  FOREIGN KEY(trail_day_id) REFERENCES trail_days(id),
  FOREIGN KEY(template_id) REFERENCES mark_templates(id),
  FOREIGN KEY(expedition_id) REFERENCES expeditions(id),
  FOREIGN KEY(milestone_id) REFERENCES milestones(id)
);
