CREATE TABLE IF NOT EXISTS media_assets (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  owner_type TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  asset_type TEXT NOT NULL,
  local_uri TEXT,
  thumbnail_uri TEXT,
  remote_uri TEXT,
  backup_status TEXT,
  file_name TEXT NOT NULL,
  mime_type TEXT,
  storage_path TEXT NOT NULL,
  thumbnail_path TEXT,
  backup_path TEXT,
  width INTEGER,
  height INTEGER,
  size_bytes INTEGER,
  byte_size INTEGER,
  captured_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0
);
