CREATE TABLE IF NOT EXISTS exercise_definitions (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT,
  path_id TEXT,
  name TEXT NOT NULL,
  title TEXT NOT NULL,
  canonical_slug TEXT NOT NULL,
  category TEXT NOT NULL,
  measurement_type TEXT NOT NULL,
  target_type TEXT NOT NULL,
  default_rest_sec INTEGER,
  default_unit TEXT,
  equipment TEXT,
  is_system INTEGER NOT NULL DEFAULT 0,
  description TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(path_id) REFERENCES paths(id)
);

CREATE TABLE IF NOT EXISTS workout_routine_templates (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  path_id TEXT NOT NULL,
  mark_template_id TEXT,
  title TEXT NOT NULL,
  routine_type TEXT NOT NULL,
  description TEXT,
  cycle_key TEXT,
  estimated_duration_min INTEGER,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(path_id) REFERENCES paths(id),
  FOREIGN KEY(mark_template_id) REFERENCES mark_templates(id)
);

CREATE TABLE IF NOT EXISTS routine_exercise_templates (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  workout_routine_template_id TEXT NOT NULL,
  exercise_definition_id TEXT NOT NULL,
  phase TEXT NOT NULL,
  order_index INTEGER NOT NULL,
  target_type TEXT NOT NULL,
  target_load_kg REAL,
  target_reps INTEGER,
  target_sets INTEGER,
  target_duration_sec INTEGER,
  target_distance_m INTEGER,
  target_steps INTEGER,
  rest_duration_sec INTEGER,
  progression_policy_json TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(workout_routine_template_id) REFERENCES workout_routine_templates(id),
  FOREIGN KEY(exercise_definition_id) REFERENCES exercise_definitions(id)
);

CREATE TABLE IF NOT EXISTS workout_session_instances (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  mark_instance_id TEXT NOT NULL,
  routine_template_id TEXT NOT NULL,
  status TEXT NOT NULL,
  phase TEXT NOT NULL,
  started_at INTEGER,
  completed_at INTEGER,
  current_exercise_snapshot_id TEXT,
  current_set_number INTEGER,
  notes TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(mark_instance_id) REFERENCES mark_instances(id),
  FOREIGN KEY(routine_template_id) REFERENCES workout_routine_templates(id)
);

CREATE TABLE IF NOT EXISTS session_exercise_snapshots (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  workout_session_instance_id TEXT NOT NULL,
  routine_exercise_template_id TEXT,
  exercise_definition_id TEXT NOT NULL,
  exercise_name_snapshot TEXT NOT NULL,
  phase TEXT NOT NULL,
  order_index INTEGER NOT NULL,
  target_type TEXT NOT NULL,
  target_load_kg REAL,
  target_reps INTEGER,
  target_sets INTEGER,
  target_duration_sec INTEGER,
  target_distance_m INTEGER,
  target_steps INTEGER,
  was_overridden INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  started_at INTEGER,
  completed_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(workout_session_instance_id) REFERENCES workout_session_instances(id),
  FOREIGN KEY(routine_exercise_template_id) REFERENCES routine_exercise_templates(id),
  FOREIGN KEY(exercise_definition_id) REFERENCES exercise_definitions(id)
);

CREATE TABLE IF NOT EXISTS exercise_set_logs (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  session_exercise_snapshot_id TEXT NOT NULL,
  set_number INTEGER NOT NULL,
  actual_load_kg REAL,
  actual_reps INTEGER,
  actual_duration_sec INTEGER,
  actual_distance_m INTEGER,
  actual_steps INTEGER,
  completed INTEGER NOT NULL DEFAULT 0,
  failed_reason TEXT,
  started_at INTEGER,
  completed_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(session_exercise_snapshot_id) REFERENCES session_exercise_snapshots(id)
);

CREATE TABLE IF NOT EXISTS exercise_progress_states (
  id TEXT PRIMARY KEY NOT NULL,
  user_id TEXT NOT NULL,
  exercise_definition_id TEXT NOT NULL,
  current_load_kg REAL,
  current_reps INTEGER,
  current_duration_sec INTEGER,
  current_distance_m INTEGER,
  current_steps INTEGER,
  current_target_load_kg REAL,
  current_target_reps INTEGER,
  current_target_sets INTEGER,
  current_target_duration_sec INTEGER,
  current_target_distance_m INTEGER,
  current_target_steps INTEGER,
  success_count_since_progression INTEGER NOT NULL DEFAULT 0,
  last_session_result TEXT,
  last_progressed_at INTEGER,
  manual_override INTEGER NOT NULL DEFAULT 0,
  last_session_at INTEGER,
  last_progression_outcome TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  deleted_at INTEGER,
  sync_status TEXT NOT NULL DEFAULT 'local',
  local_revision INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY(exercise_definition_id) REFERENCES exercise_definitions(id)
);
