import type { WeeklyTimetableImportSlotInput } from "../src/lib/waymark/weeklyTimetableImport";

function slot(
  localDate: string,
  startTime: string,
  endTime: string,
  title: string,
  pathRef: string,
  blockKey: string,
  expeditionRef?: string,
  milestoneRef?: string,
  note?: string,
): WeeklyTimetableImportSlotInput {
  return {
    localDate,
    startTime,
    endTime,
    title,
    pathRef,
    blockKey,
    expeditionRef,
    milestoneRef,
    note,
  };
}

export const WEEKLY_TIMETABLE_IMPORT_FIXTURE: WeeklyTimetableImportSlotInput[] = [
  slot("2026-05-30", "05:30", "07:00", "Workout Day B", "Health & Body", "workout", "Cut to 70", "Workout session", "Workout mark imported from weekly timetable"),
  slot("2026-05-30", "08:00", "11:15", "Family Morning — Đi hội chợ kem Hà Nội tại Cung Văn hóa Hữu nghị", "Family & Home", "morning_family", "Family Weekend", "Weekend family activity", "Sáng đi hội chợ kem Hà Nội tại Cung Văn hóa Hữu nghị"),
  slot("2026-05-30", "13:30", "16:45", "Family Afternoon — Cả nhà chơi với nhau", "Family & Home", "afternoon_family", "Family Weekend", "Weekend family activity", "Chiều cả nhà chơi với nhau, không nhồi thêm việc"),
  slot("2026-05-30", "20:00", "21:00", "Học tiếng Anh nhẹ / đọc sách", "Family & Home", "evening_activity", "Dạy con Tiếng Anh", "Evening study", "Hoạt động nhẹ buổi tối"),
  slot("2026-05-31", "05:30", "07:00", "Workout Walk", "Health & Body", "workout", "Cut to 70", "Recovery walk", "Workout mark imported from weekly timetable"),
  slot("2026-05-31", "08:00", "11:15", "Family Morning — Về cụ làm cỗ", "Family & Home", "morning_family", "Family Weekend", "Family duty", "Sáng về cụ, làm cỗ, trách nhiệm gia đình"),
  slot("2026-05-31", "13:30", "16:45", "Family Afternoon — Đi nhà sách Tân Việt bằng voucher", "Family & Home", "afternoon_family", "Family Weekend", "Weekend family activity", "Chiều đi nhà sách Tân Việt, dùng voucher, chọn sách cho con"),
  slot("2026-05-31", "20:00", "21:00", "Trông con làm bài về nhà môn Toán + Tiếng Việt", "Family & Home", "evening_activity", "Family Study", "Hôm sau học tiền tiểu học", "Theo lịch học của con: Thứ 2 học tiền tiểu học Toán + Tiếng Việt"),
  slot("2026-06-01", "05:30", "07:00", "Workout Day A", "Health & Body", "workout", "Cut to 70", "Workout session", "Workout mark imported from weekly timetable"),
  slot("2026-06-01", "08:00", "09:30", "Execute Testcase — PHT GNQT Luồng KHCN thẻ phụ", "Career", "morning_activity", "SCH Smart Counter Hub Project", "Phát hànhThẻ GNQT — Ghép luồng Onboarding", "Proof: evidence test + bug list nếu có"),
  slot("2026-06-01", "09:45", "11:15", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_am", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-01", "13:30", "15:00", "Execute Testcase — PHT GNQT Luồng KHCN làm mịn", "Career", "afternoon_activity", "SCH Smart Counter Hub Project", "Phát hànhThẻ GNQT — Ghép luồng Onboarding", "Proof: evidence test + issue/gap list nếu có"),
  slot("2026-06-01", "15:15", "16:45", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_pm", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-01", "17:00", "18:30", "Cập nhật và Ký duyệt RSD biểu mẫu", "Career", "final_focus", "SCH Smart Counter Hub Project", "RSD biểu mẫu", "Proof: RSD cập nhật, tình trạng ký duyệt hoặc blocker"),
  slot("2026-06-01", "20:00", "21:00", "Trông con làm bài về nhà môn Toán + Tiếng Việt", "Family & Home", "evening_activity", "Family Study", "Hôm sau học tiền tiểu học", "Theo lịch học của con: Thứ 2 học tiền tiểu học Toán + Tiếng Việt"),
  slot("2026-06-02", "05:30", "07:00", "Workout Day B", "Health & Body", "workout", "Cut to 70", "Workout session", "Workout mark imported from weekly timetable"),
  slot("2026-06-02", "08:00", "09:30", "Execute Testcase — PHT GNQT Luồng KHTC hiện hữu", "Career", "morning_activity", "SCH Smart Counter Hub Project", "Phát hànhThẻ GNQT — Ghép luồng Onboarding", "Proof: evidence test KHTC hiện hữu + bug list nếu có"),
  slot("2026-06-02", "09:45", "11:15", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_am", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-02", "13:30", "15:00", "Execute Testcase — PHT GNQT Luồng KHTC mở mới", "Career", "afternoon_activity", "SCH Smart Counter Hub Project", "Phát hànhThẻ GNQT — Ghép luồng Onboarding", "Proof: evidence test KHTC mở mới + bug list nếu có"),
  slot("2026-06-02", "15:15", "16:45", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_pm", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-02", "17:00", "18:30", "Viết Testcase — PHT GNQT Luồng KHTC", "Career", "final_focus", "SCH Smart Counter Hub Project", "Phát hànhThẻ GNQT — Ghép luồng Onboarding", "Một bộ testcase KHTC; không tách thành KHTC hiện hữu/mở mới. Hai nhánh nằm trong note/checklist"),
  slot("2026-06-02", "20:00", "21:00", "Học tiếng Anh / đọc sách ngữ pháp", "Family & Home", "evening_activity", "Dạy con Tiếng Anh", "Evening study", "Không có môn cụ thể hôm sau; học tiếng Anh/đọc sách ngữ pháp"),
  slot("2026-06-03", "05:30", "07:00", "Workout Walk", "Health & Body", "workout", "Cut to 70", "Recovery walk", "Workout mark imported from weekly timetable"),
  slot("2026-06-03", "08:00", "09:30", "Waymark Anniversary — Refactor phần Cloud DB", "Family & Home", "morning_activity", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: refactor note, điểm đã sửa, blocker nếu có"),
  slot("2026-06-03", "09:45", "11:15", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_am", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-03", "13:30", "15:00", "Waymark Anniversary — Luồng vững Cloud Media lên Google Drive", "Family & Home", "afternoon_activity", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: media upload flow, Drive mapping, failure handling note"),
  slot("2026-06-03", "15:15", "16:45", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_pm", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-03", "17:00", "18:30", "Waymark Anniversary — UI Assets Skins cho Anniversary edition", "Family & Home", "final_focus", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: asset checklist + mapping skin"),
  slot("2026-06-03", "20:00", "21:00", "Học tiếng Anh / đọc sách ngữ pháp", "Family & Home", "evening_activity", "Dạy con Tiếng Anh", "Evening study", "Không có môn cụ thể hôm sau; học tiếng Anh/đọc sách ngữ pháp"),
  slot("2026-06-04", "05:30", "07:00", "Workout Day A", "Health & Body", "workout", "Cut to 70", "Workout session", "Workout mark imported from weekly timetable"),
  slot("2026-06-04", "08:00", "09:30", "Dữ liệu kỷ niệm — Inventory mốc 11 năm", "Family & Home", "morning_activity", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: danh sách năm/giai đoạn/mốc cần nhập"),
  slot("2026-06-04", "09:45", "11:15", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_am", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-04", "13:30", "15:00", "Dữ liệu kỷ niệm — Batch 1: giai đoạn đầu", "Family & Home", "afternoon_activity", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: memory items đã chuẩn hóa cho giai đoạn đầu"),
  slot("2026-06-04", "15:15", "16:45", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_pm", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-04", "17:00", "18:30", "Dữ liệu kỷ niệm — Batch 2: giai đoạn giữa", "Family & Home", "final_focus", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: memory items đã chuẩn hóa cho giai đoạn giữa"),
  slot("2026-06-04", "20:00", "21:00", "Trông con ôn Tiếng Anh Cambridge", "Family & Home", "evening_activity", "Family Study", "Hôm sau học Tiếng Anh Cambridge", "Theo lịch học của con: Thứ 6 học Tiếng Anh Cambridge"),
  slot("2026-06-05", "05:30", "07:00", "Workout Day B", "Health & Body", "workout", "Cut to 70", "Workout session", "Workout mark imported from weekly timetable"),
  slot("2026-06-05", "08:00", "09:30", "Dữ liệu kỷ niệm — Batch 3: giai đoạn gần đây", "Family & Home", "morning_activity", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: memory items đã chuẩn hóa cho giai đoạn gần đây"),
  slot("2026-06-05", "09:45", "11:15", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_am", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-05", "13:30", "15:00", "Dữ liệu kỷ niệm — Batch 4: giai đoạn hiện tại", "Family & Home", "afternoon_activity", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: memory items đã chuẩn hóa cho giai đoạn hiện tại"),
  slot("2026-06-05", "15:15", "16:45", "Supervising Block — Check Zalo, mail, Confluence, Jira", "Career", "supervising_pm", "Supervising", "Daily supervising", "Supervising cố định, không thay bằng focus work"),
  slot("2026-06-05", "17:00", "18:30", "Dữ liệu kỷ niệm — Review & chuẩn hóa metadata", "Family & Home", "final_focus", "Building Waymark", "Xây dựng Waymark Anniversary edition", "Proof: title/date/note/media/source đã chuẩn hóa"),
  slot("2026-06-05", "20:00", "21:00", "Trông con ôn Tiếng Anh Cambridge", "Family & Home", "evening_activity", "Family Study", "Hôm sau học Tiếng Anh Cambridge", "Theo lịch học của con: Thứ 7 học Tiếng Anh Cambridge"),
  slot("2026-06-06", "05:30", "07:00", "Workout Walk", "Health & Body", "workout", "Cut to 70", "Recovery walk", "Workout mark imported from weekly timetable"),
  slot("2026-06-06", "08:00", "11:15", "Family Morning — Ở nhà nhẹ / chơi với con / chuẩn bị về cụ ngoại", "Family & Home", "morning_family", "Family Weekend", "Weekend family activity", "Không đặt Career/Waymark work mark vào Thứ 7"),
  slot("2026-06-06", "13:30", "16:45", "Family Afternoon — Về cụ ngoại", "Family & Home", "afternoon_family", "Family Weekend", "Weekend family activity", "Chiều Thứ 7 về cụ ngoại; ưu tiên gia đình"),
  slot("2026-06-06", "17:00", "18:30", "Family Final — Nghỉ / ăn tối cùng gia đình", "Family & Home", "family_final", "Family Weekend", "Weekend recovery", "Nghỉ và ăn tối gia đình; không làm việc"),
  slot("2026-06-06", "20:00", "21:00", "Học tiếng Anh nhẹ / đọc sách", "Family & Home", "evening_activity", "Family Study", "Evening light study", "Hoạt động nhẹ buổi tối"),
  slot("2026-06-07", "05:30", "07:00", "Workout Day A", "Health & Body", "workout", "Cut to 70", "Workout session", "Workout mark imported from weekly timetable"),
  slot("2026-06-07", "08:00", "11:15", "Family Morning — Con học vẽ", "Family & Home", "morning_family", "Family Weekend", "Weekend family activity", "Bảo vệ lịch học vẽ sáng Chủ nhật của con"),
  slot("2026-06-07", "13:30", "16:45", "Family Afternoon — Chơi nhẹ với con / nghỉ phục hồi / nhà sách gần nhà nếu còn sức", "Family & Home", "afternoon_family", "Family Weekend", "Weekend family activity", "Giữ chiều Chủ nhật nhẹ để chuẩn bị tuần mới"),
  slot("2026-06-07", "17:00", "18:30", "Weekly Reset — chuẩn bị tuần mới", "Family & Home", "family_final", "Weekly Readiness", "Weekly reset", "Cặp sách, đồ đi làm, đồ tập, review tuần sau"),
  slot("2026-06-07", "20:00", "21:00", "Trông con làm bài về nhà môn Toán + Tiếng Việt", "Family & Home", "evening_activity", "Family Study", "Hôm sau học tiền tiểu học", "Theo lịch học của con: Thứ 2 học tiền tiểu học Toán + Tiếng Việt"),
];

export const WEEKLY_TIMETABLE_EXPECTED_COUNTS: Record<string, number> = {
  "2026-05-30": 4,
  "2026-05-31": 4,
  "2026-06-01": 7,
  "2026-06-02": 7,
  "2026-06-03": 7,
  "2026-06-04": 7,
  "2026-06-05": 7,
  "2026-06-06": 5,
  "2026-06-07": 5,
};
