import { Locale } from "../../../types/ui";
import { todayPathHeroPaths } from "../../../lib/waymark/todayPathHero";
import { TodayCockpitFeatureFlags, TodayCockpitScreenProps } from "../TodayCockpitScreen";
import { todayMarksFixture, todayMarksAllDoneFixture, todayPackChecksFixture } from "./todayCarousel.fixtures";
import { currentExpeditionFixtures, closeTrailFixtures } from "./todayExpedition.fixtures";

export type TodayCockpitFixture = {
  id: string;
  title: string;
  locale?: Locale;
  frameWidth?: number;
  screenProps: Omit<TodayCockpitScreenProps, "locale" | "withShell">;
};

const allVisibleFlags: TodayCockpitFeatureFlags = {
  isPathHeroEnabled: true,
  isPathDetailEnabled: true,
  isMarksEnabled: true,
  isMarkDetailEnabled: true,
  isIndependentPackChecksEnabled: true,
  isPrepareTomorrowEnabled: true,
  isPackCheckDetailEnabled: true,
  isCurrentExpeditionEnabled: true,
  isExpeditionDetailEnabled: true,
  isCloseTrailEnabled: true,
};

const hiddenFlags: TodayCockpitFeatureFlags = {
  isPathHeroEnabled: false,
  isPathDetailEnabled: false,
  isMarksEnabled: false,
  isMarkDetailEnabled: false,
  isIndependentPackChecksEnabled: false,
  isPrepareTomorrowEnabled: false,
  isPackCheckDetailEnabled: false,
  isCurrentExpeditionEnabled: false,
  isExpeditionDetailEnabled: false,
  isCloseTrailEnabled: false,
};

export const todayCockpitFixtures: TodayCockpitFixture[] = [
  {
    id: "standard",
    title: "Standard Today",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: currentExpeditionFixtures[0].expeditions,
      featureFlags: allVisibleFlags,
      marks: todayMarksFixture,
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "all-done",
    title: "All marks done",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: currentExpeditionFixtures[0].expeditions,
      featureFlags: allVisibleFlags,
      marks: todayMarksAllDoneFixture,
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "no-marks",
    title: "No marks",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: currentExpeditionFixtures[0].expeditions,
      featureFlags: allVisibleFlags,
      marks: [],
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "pack-count-zero",
    title: "Pack count 0",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: currentExpeditionFixtures[0].expeditions,
      featureFlags: allVisibleFlags,
      marks: todayMarksFixture,
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "no-expeditions",
    title: "No current expeditions",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: [],
      featureFlags: allVisibleFlags,
      marks: todayMarksFixture,
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "close-trail-completed",
    title: "Close the Trail completed",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[1].status,
      currentExpeditions: currentExpeditionFixtures[0].expeditions,
      featureFlags: allVisibleFlags,
      marks: todayMarksFixture,
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "gated-hidden",
    title: "Feature gated",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: [],
      featureFlags: hiddenFlags,
      marks: [],
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: [],
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "vietnamese",
    title: "Vietnamese locale",
    locale: "vi",
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: currentExpeditionFixtures[0].expeditions,
      featureFlags: allVisibleFlags,
      marks: todayMarksFixture,
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
  {
    id: "narrow",
    title: "Narrow viewport",
    frameWidth: 320,
    screenProps: {
      closeTrailStatus: closeTrailFixtures[0].status,
      currentExpeditions: currentExpeditionFixtures[0].expeditions,
      featureFlags: allVisibleFlags,
      marks: todayMarksFixture,
      onOpenCloseTrail: undefined,
      onOpenExpedition: undefined,
      onOpenMarkDetail: undefined,
      onOpenPackCheck: undefined,
      onOpenPathDetail: undefined,
      packChecks: todayPackChecksFixture,
      paths: todayPathHeroPaths,
      selectedPathId: "family",
      onPathChange: () => undefined,
    },
  },
];
